services:
  app:
    build:
      context: .
      dockerfile: docker/production/app/Dockerfile
    container_name: flip-catalog-parser-app
    ports:
      - "8000:8000"
      - "5900:5900"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      VNC_PASSWORD: ${VNC_PASSWORD}
      POSTGRES_DSN: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      MODE: production
    
  database:
    image: postgres:16
    container_name: flip-catalog-parser-database
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgresql_data: