services:
  app:
    build:
      context: .
      dockerfile: docker/development/app/Dockerfile
    command: tail -f /dev/null
    volumes:
      - .:/flip_catalog_parser:cached
    environment:
      MODE: development